#pragma once

/// @file message.h
/// @brief Message types for communication between engine threads.
///
/// Messages are designed to be small, trivially copyable POD types suitable
/// for passing through the lock-free SPSC queue. Two variant types define
/// the engine boundary:
///   - EngineMessage:  messages flowing INTO the matching engine (orders, cancels)
///   - OutputMessage:  messages flowing OUT of the engine (fills, book updates)

#include <variant>
#include "core/types.h"

namespace engine {

// ---------------------------------------------------------------------------
// Inbound messages (feed → engine)
// ---------------------------------------------------------------------------

/// @brief Request to place a new order.
struct NewOrderMessage {
    OrderId   id        = 0;                 ///< Client-assigned order ID
    Side      side      = Side::Bid;         ///< Buy or sell
    OrderType type      = OrderType::Limit;  ///< Limit or market
    Price     price     = 0;                 ///< Price in ticks (ignored for market orders)
    Quantity  quantity   = 0;                 ///< Order quantity
    Timestamp timestamp = 0;                 ///< Submission timestamp (ns since epoch)
};

/// @brief Request to cancel an existing order.
struct CancelMessage {
    OrderId   id        = 0;  ///< ID of the order to cancel
    Timestamp timestamp = 0;  ///< Cancel request timestamp (ns since epoch)
};

// ---------------------------------------------------------------------------
// Outbound messages (engine → output)
// ---------------------------------------------------------------------------

/// @brief A trade/fill event generated by the matching engine.
struct FillMessage {
    OrderId   aggressive_id = 0;  ///< The incoming (taker) order ID
    OrderId   passive_id    = 0;  ///< The resting (maker) order ID
    Price     price         = 0;  ///< Execution price in ticks
    Quantity  quantity      = 0;  ///< Fill quantity
    Timestamp timestamp     = 0;  ///< Fill timestamp (ns since epoch)
};

/// @brief Notification of a change in the order book at a specific price level.
struct BookUpdateMessage {
    Side     side               = Side::Bid;  ///< Which side of the book changed
    Price    price              = 0;          ///< Price level that changed (in ticks)
    Quantity new_total_quantity = 0;          ///< New total quantity at this level
};

// ---------------------------------------------------------------------------
// Tagged message unions
// ---------------------------------------------------------------------------

/// Messages going INTO the matching engine (from feed/input thread).
using EngineMessage = std::variant<NewOrderMessage, CancelMessage>;

/// Messages coming OUT of the matching engine (to output/logging thread).
using OutputMessage = std::variant<FillMessage, BookUpdateMessage>;

} // namespace engine
